package org.unitec;

import javax.swing.JOptionPane;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.unitec//Principal//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "PrincipalTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "org.unitec.PrincipalTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_PrincipalAction",
        preferredID = "PrincipalTopComponent"
)
@Messages({
    "CTL_PrincipalAction=Principal",
    "CTL_PrincipalTopComponent=Principal Window",
    "HINT_PrincipalTopComponent=This is a Principal window"
})
public final class PrincipalTopComponent extends TopComponent {
    Recta recta = new Recta();
    Parabola parabola = new Parabola();
    Hiperbola hiperbola = new Hiperbola();
    Seno seno = new Seno();
    
    public PrincipalTopComponent() {
        initComponents();
        setName(Bundle.CTL_PrincipalTopComponent());
        setToolTipText(Bundle.HINT_PrincipalTopComponent());
        
        PanelGrafica.add(recta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        PanelGrafica = new javax.swing.JPanel();
        contenedorEcuaciones = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        txtA = new javax.swing.JTextField();
        lblY = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblEcuacionRecta = new javax.swing.JLabel();
        btnGraficarRecta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblEcuacionRecta1 = new javax.swing.JLabel();
        lblY1 = new javax.swing.JLabel();
        txtParabolaA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtParabolaB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnGraficarParabola = new javax.swing.JButton();
        txtParabolaC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtAHiperbola = new javax.swing.JTextField();
        lblEcuacionRecta2 = new javax.swing.JLabel();
        lblY2 = new javax.swing.JLabel();
        txtBHiperbola = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGraficarHiperbola = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lblEcuacionRecta3 = new javax.swing.JLabel();
        lblY3 = new javax.swing.JLabel();
        txtBSen = new javax.swing.JTextField();
        btnGraficarSen = new javax.swing.JButton();
        txtCSen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtASen = new javax.swing.JTextField();
        lblY4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();

        org.openide.awt.Mnemonics.setLocalizedText(lblTitulo, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.lblTitulo.text")); // NOI18N

        PanelGrafica.setBackground(new java.awt.Color(0, 102, 255));
        PanelGrafica.setLayout(new java.awt.BorderLayout());

        contenedorEcuaciones.setBackground(new java.awt.Color(204, 204, 255));
        contenedorEcuaciones.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.jLabel2.text")); // NOI18N

        txtB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtB.setText(org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.txtB.text")); // NOI18N

        txtA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtA.setText(org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.txtA.text")); // NOI18N

        lblY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(lblY, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.lblY.text")); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.jLabel1.text")); // NOI18N

        lblEcuacionRecta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(lblEcuacionRecta, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.lblEcuacionRecta.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnGraficarRecta, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.btnGraficarRecta.text")); // NOI18N
        btnGraficarRecta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarRectaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEcuacionRecta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(lblY)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGraficarRecta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblEcuacionRecta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblY)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGraficarRecta)
                .addGap(463, 463, 463))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        lblEcuacionRecta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(lblEcuacionRecta1, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.lblEcuacionRecta1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblY1, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.lblY1.text")); // NOI18N

        txtParabolaA.setText(org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.txtParabolaA.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.jLabel3.text")); // NOI18N

        txtParabolaB.setText(org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.txtParabolaB.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnGraficarParabola, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.btnGraficarParabola.text")); // NOI18N
        btnGraficarParabola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarParabolaActionPerformed(evt);
            }
        });

        txtParabolaC.setText(org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.txtParabolaC.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.jLabel6.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEcuacionRecta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblY1)
                .addGap(4, 4, 4)
                .addComponent(txtParabolaA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGraficarParabola)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParabolaB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParabolaC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(76, 76, 76))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblEcuacionRecta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblY1)
                    .addComponent(txtParabolaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtParabolaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtParabolaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGraficarParabola)
                .addContainerGap(469, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        txtAHiperbola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAHiperbola.setText(org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.txtAHiperbola.text")); // NOI18N

        lblEcuacionRecta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(lblEcuacionRecta2, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.lblEcuacionRecta2.text")); // NOI18N

        lblY2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(lblY2, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.lblY2.text")); // NOI18N

        txtBHiperbola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBHiperbola.setText(org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.txtBHiperbola.text")); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.jLabel5.text")); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.jLabel7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnGraficarHiperbola, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.btnGraficarHiperbola.text")); // NOI18N
        btnGraficarHiperbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarHiperbolaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEcuacionRecta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblY2)
                        .addGap(4, 4, 4)
                        .addComponent(txtAHiperbola, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBHiperbola, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnGraficarHiperbola, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblEcuacionRecta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblY2)
                    .addComponent(txtAHiperbola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtBHiperbola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGraficarHiperbola)
                .addGap(463, 463, 463))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.jPanel4.TabConstraints.tabTitle"), jPanel4); // NOI18N

        lblEcuacionRecta3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(lblEcuacionRecta3, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.lblEcuacionRecta3.text")); // NOI18N

        lblY3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(lblY3, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.lblY3.text")); // NOI18N

        txtBSen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBSen.setText(org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.txtBSen.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnGraficarSen, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.btnGraficarSen.text")); // NOI18N
        btnGraficarSen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarSenActionPerformed(evt);
            }
        });

        txtCSen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCSen.setText(org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.txtCSen.text")); // NOI18N

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.jLabel8.text")); // NOI18N

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.jLabel9.text")); // NOI18N

        txtASen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtASen.setText(org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.txtASen.text")); // NOI18N

        lblY4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(lblY4, org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.lblY4.text")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEcuacionRecta3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGraficarSen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblY4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtASen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblY3)
                        .addGap(4, 4, 4)
                        .addComponent(txtBSen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCSen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblEcuacionRecta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblY3)
                    .addComponent(txtBSen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtCSen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtASen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblY4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGraficarSen)
                .addGap(463, 463, 463))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.jPanel6.TabConstraints.tabTitle"), jPanel6); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(PrincipalTopComponent.class, "PrincipalTopComponent.jPanel8.TabConstraints.tabTitle"), jPanel8); // NOI18N

        contenedorEcuaciones.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contenedorEcuaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedorEcuaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(PanelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficarParabolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarParabolaActionPerformed
        // TODO add your handling code here:
        
        try{
            PanelGrafica.removeAll();
            
            float a = Float.parseFloat(txtParabolaA.getText());
            float b = Float.parseFloat(txtParabolaB.getText());
            float c = Float.parseFloat(txtParabolaC.getText());
            
            parabola.a = a;
            parabola.b = b;
            parabola.c = c;
                                
            PanelGrafica.add(parabola);
            PanelGrafica.updateUI();
            repaint();
            
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Ingresa un número válido.");
        }
    }//GEN-LAST:event_btnGraficarParabolaActionPerformed

    private void btnGraficarRectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarRectaActionPerformed
        // TODO add your handling code here:
        
        try{
            PanelGrafica.removeAll();
            
            float a = Float.parseFloat(txtA.getText());
            float b = Float.parseFloat(txtB.getText());

            recta.a = a;
            recta.b = b;
            
            PanelGrafica.add(recta);
            PanelGrafica.updateUI();
            repaint();
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Ingresa un número válido.");
        }
    }//GEN-LAST:event_btnGraficarRectaActionPerformed

    private void btnGraficarHiperbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarHiperbolaActionPerformed
        // TODO add your handling code here:
        
        try{
            PanelGrafica.removeAll();
            
            float a = Float.parseFloat(txtAHiperbola.getText());
            float b = Float.parseFloat(txtBHiperbola.getText());

            hiperbola.a = a;
            hiperbola.b = b;
            
            PanelGrafica.add(hiperbola);
            PanelGrafica.updateUI();
            repaint();
            
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Ingresa un número válido.");
        }
    }//GEN-LAST:event_btnGraficarHiperbolaActionPerformed

    private void btnGraficarSenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarSenActionPerformed
        // TODO add your handling code here:
        
        try{
            PanelGrafica.removeAll();
            
            float a = Float.parseFloat(txtASen.getText());
            float b = Float.parseFloat(txtBSen.getText());
            float c = Float.parseFloat(txtCSen.getText());
            
            seno.a = a;
            seno.b = b;
            seno.c = c;
            
            PanelGrafica.add(seno);
            PanelGrafica.updateUI();
            repaint();
            
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Ingresa un número válido.");
        }
    }//GEN-LAST:event_btnGraficarSenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGrafica;
    private javax.swing.JButton btnGraficarHiperbola;
    private javax.swing.JButton btnGraficarParabola;
    private javax.swing.JButton btnGraficarRecta;
    private javax.swing.JButton btnGraficarSen;
    private javax.swing.JPanel contenedorEcuaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEcuacionRecta;
    private javax.swing.JLabel lblEcuacionRecta1;
    private javax.swing.JLabel lblEcuacionRecta2;
    private javax.swing.JLabel lblEcuacionRecta3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblY;
    private javax.swing.JLabel lblY1;
    private javax.swing.JLabel lblY2;
    private javax.swing.JLabel lblY3;
    private javax.swing.JLabel lblY4;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtAHiperbola;
    private javax.swing.JTextField txtASen;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtBHiperbola;
    private javax.swing.JTextField txtBSen;
    private javax.swing.JTextField txtCSen;
    private javax.swing.JTextField txtParabolaA;
    private javax.swing.JTextField txtParabolaB;
    private javax.swing.JTextField txtParabolaC;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
